import React,{useMemo,useState} from 'react';
import Icon from '../components/Icon.jsx';
import {GAMES} from '../data/games.js';
import {useLanguage} from '../context/LanguageContext.jsx';
import {useArena} from '../context/ArenaContext.jsx';
export default function ArenaBuilder({onNavigate}){
 const {lang}=useLanguage();const copy=(id,en)=>lang==='id'?id:en;const {startCustomArenaRun,setNotice}=useArena();
 const [selected,setSelected]=useState(()=>GAMES.slice(0,5).map(g=>g.id));const [mode,setMode]=useState('ranked');const [level,setLevel]=useState('universitas');const [difficulty,setDifficulty]=useState('hard');const [order,setOrder]=useState('random');
 const games=useMemo(()=>GAMES.filter(g=>selected.includes(g.id)),[selected]);
 const toggle=id=>setSelected(prev=>prev.includes(id)?prev.filter(x=>x!==id):prev.length>=12?prev:[...prev,id]);
 const start=()=>{if(selected.length<3){setNotice(copy('Pilih minimal 3 game','Choose at least 3 games'));return;}const run=startCustomArenaRun({gameIds:selected,mode,schoolLevel:level,universityDifficulty:difficulty,randomize:order==='random'});if(run)onNavigate(run.stages[0].gameId);};
 return <div className="meta-page arena-builder-page"><div className="page-heading"><div><span className="eyebrow">CUSTOM ARENA BUILDER</span><h1>{copy('Bangun turnamenmu sendiri.','Build your own tournament.')}</h1><p className="page-intro">{copy('Pilih 3–12 game, mode, tingkat, dan urutan arena.','Choose 3–12 games, mode, difficulty, and arena order.')}</p></div></div>
 <div className="builder-layout"><section className="builder-games"><div className="section-heading"><h2>{copy('Pilih game','Choose games')} <span className="count-badge">{selected.length}/12</span></h2></div><div className="builder-game-grid">{GAMES.map(g=><button key={g.id} className={selected.includes(g.id)?'selected':''} onClick={()=>toggle(g.id)}><span className={`mini-game-icon color-${g.color}`}><Icon name={g.icon}/></span><span>{g.title[lang]}</span><Icon name={selected.includes(g.id)?'check':'plus'} size={15}/></button>)}</div></section>
 <aside className="builder-options"><h2>{copy('Aturan arena','Arena rules')}</h2><label><span>Mode</span><select value={mode} onChange={e=>setMode(e.target.value)}><option value="ranked">Ranked</option><option value="practice">Practice</option></select></label><label><span>{copy('Jenjang','Level')}</span><select value={level} onChange={e=>setLevel(e.target.value)}><option value="sd">SD</option><option value="smp">SMP</option><option value="sma">SMA</option><option value="universitas">Universitas</option></select></label>{level==='universitas'&&<label><span>Arena Mode</span><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="hard">Hard</option><option value="very-hard">Very Hard</option><option value="impossible">Impossible</option></select></label>}<label><span>{copy('Urutan','Order')}</span><select value={order} onChange={e=>setOrder(e.target.value)}><option value="random">{copy('Acak','Random')}</option><option value="manual">{copy('Sesuai pilihan','Selection order')}</option></select></label><div className="builder-summary"><small>{copy('ARENA TERPILIH','SELECTED ARENA')}</small>{games.map((g,i)=><span key={g.id}><b>{i+1}</b>{g.title[lang]}</span>)}</div><button className="ba-button primary full-width" onClick={start}>{copy('Mulai Custom Arena','Start Custom Arena')}<Icon name="arrow" size={15}/></button></aside></div></div>;
}
