import React,{useMemo,useState} from 'react';
import Icon from '../components/Icon.jsx';
import {GAMES,gameById} from '../data/games.js';
import {useLanguage} from '../context/LanguageContext.jsx';
import {useArena} from '../context/ArenaContext.jsx';
import {getDailyChallenge,localDateKey,shiftDateKey} from '../utils/progression.js';
export default function DailyArchive({onNavigate}){
 const {lang}=useLanguage();const copy=(id,en)=>lang==='id'?id:en;const {daily,setChallengeCode,setNotice}=useArena();const today=localDateKey();const [selected,setSelected]=useState(today);
 const days=useMemo(()=>Array.from({length:30},(_,i)=>shiftDateKey(today,-i)),[today]);const item=getDailyChallenge(GAMES,selected);const game=gameById(item.gameId);const complete=Boolean(daily.completedByDate?.[selected]);
 const play=()=>{if(selected!==today){setChallengeCode(game.id,`BA-${game.id.toUpperCase()}-${selected.replaceAll('-','')}`);setNotice(copy('Archive mode: tidak menambah Daily Streak','Archive mode: does not extend Daily Streak'));}onNavigate(game.id);};
 return <div className="meta-page daily-archive-page"><div className="page-heading"><div><span className="eyebrow">DAILY ARCHIVE</span><h1>{copy('Kembali ke tantangan sebelumnya.','Revisit past daily challenges.')}</h1><p className="page-intro">{copy('Challenge lama bisa dimainkan ulang, tetapi tidak menambah streak hari ini.','Past challenges can be replayed, but they do not extend today’s streak.')}</p></div></div><div className="archive-layout"><section className="archive-calendar">{days.map(key=><button key={key} className={`${selected===key?'selected':''} ${daily.completedByDate?.[key]?'complete':''}`} onClick={()=>setSelected(key)}><small>{new Date(`${key}T00:00:00`).toLocaleDateString(lang==='id'?'id-ID':'en-US',{weekday:'short'})}</small><strong>{key.slice(8)}</strong>{daily.completedByDate?.[key]&&<Icon name="check" size={12}/>}</button>)}</section><aside className="archive-detail"><span className={`mini-game-icon color-${game.color}`}><Icon name={game.icon}/></span><small>{selected}</small><h2>{game.title[lang]}</h2><p>{complete?copy('Sudah pernah diselesaikan.','Previously completed.'):copy('Belum tercatat selesai.','Not completed yet.')}</p><div className="archive-status"><Icon name={complete?'check':'clock'} size={16}/>{complete?copy('Selesai','Completed'):copy('Belum selesai','Not completed')}</div><button className="ba-button primary full-width" onClick={play}>{selected===today?copy('Mainkan Daily Hari Ini','Play Today’s Daily'):copy('Mainkan Arsip','Play Archive')}<Icon name="arrow" size={15}/></button></aside></div></div>;
}
