import React, { useMemo, useRef, useState } from 'react';
import { GAMES, CATEGORIES, gameById } from '../data/games.js';
import { useLanguage } from '../context/LanguageContext.jsx';
import { useArena } from '../context/ArenaContext.jsx';
import Icon from '../components/Icon.jsx';
import GameCard from '../components/GameCard.jsx';
import { HeroArtwork } from '../components/Artwork.jsx';
export default function Home({ onSelectGame, view = 'home' }) {
  const { lang } = useLanguage(); const { favorites, history, profile, levelInfo, todayChallenge, dailyCompleted, currentStreak } = useArena();
  const [season, setSeason] = useState('all'); const [category, setCategory] = useState('all'); const [query, setQuery] = useState('');
  const catalog = useRef(null); const home = view === 'home'; const favoriteView = view === 'favorites';
  const copy = (id, en) => lang === 'id' ? id : en;
  const baseGames = favoriteView ? GAMES.filter(g => favorites.includes(g.id)) : GAMES;
  const filtered = useMemo(() => baseGames.filter(game => (season === 'all' || game.season === Number(season)) && (category === 'all' || game.category === category) && `${game.title.id} ${game.title.en} ${game.description[lang]} ${CATEGORIES[game.category][lang]}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [baseGames, season, category, query, lang]);
  const recent = [...new Set(history.map(item => item.id))].slice(0, 3).map(gameById);
  const dailyGame = gameById(todayChallenge.gameId);
  return <div className="home-page">
    <div className="page-heading"><div><p className="eyebrow">{copy('RUANG BERMAIN, RUANG BERTUMBUH', 'A LITTLE PLAY. A LOT OF POSSIBILITIES.')}</p><h1>{favoriteView ? copy('Game favoritmu.', 'Your favorites.') : home ? copy('Siap adu pikiran?', 'Ready to outthink?') : copy('Temukan tantanganmu.', 'Find your next challenge.')}</h1><p className="page-intro">{favoriteView ? copy('Pilihan terbaikmu, terkumpul di satu tempat.', 'Your personal collection, all in one place.') : copy('Latih logika, pertajam ingatan, dan nikmati setiap tantangan.', 'Train your logic, sharpen your memory, and enjoy the challenge.')}</p></div><span className="local-label"><span/>{copy('Tanpa akun. Langsung main.', 'No sign-up. Just play.')}</span></div>
    {home && <>
      <section className="hero"><div className="hero-copy"><span className="hero-eyebrow"><span/> UNIVERSITY WAR INSPIRED</span><h2>{copy('Otak tajam.', 'Sharp minds.')}<br/><span>{copy('Mulai dari sini.', 'Start here.')}</span></h2><p>{copy('Bukan sekadar permainan. Ini arena untuk menantang batas kemampuanmu, satu langkah setiap hari.', 'More than just a game. A space to push your mind a little further, one challenge at a time.')}</p><div className="hero-actions"><button className="ba-button lime" onClick={() => catalog.current?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' })}>{copy('Jelajahi permainan', 'Explore games')}<Icon name="arrow" size={17}/></button><button className="hero-guide" onClick={() => onSelectGame('guides')}><Icon name="play" size={15}/>{copy('Cara bermain', 'How to play')}</button></div><div className="hero-note"><Icon name="check" size={14}/>{copy(`${GAMES.length} game interaktif`, `${GAMES.length} interactive games`)}<span/>{copy('Dari SD hingga universitas', 'Elementary to university')}</div></div><HeroArtwork/></section>
      <section className={`home-daily-card ${dailyCompleted ? 'is-complete' : ''}`}>
        <div className="home-daily-main"><span className={`home-daily-icon color-${dailyGame.color}`}><Icon name={dailyGame.icon} size={24}/></span><div><span className="eyebrow"><Icon name="spark" size={12}/>{copy('DAILY CHALLENGE', 'DAILY CHALLENGE')}</span><h2>{dailyCompleted ? copy('Tantangan hari ini selesai!', 'Today’s challenge is complete!') : dailyGame.title[lang]}</h2><p>{dailyCompleted ? copy('Bonus harian sudah diamankan. Kamu tetap bisa bermain lagi untuk XP sesi.', 'Your daily bonus is secured. You can still play again for session XP.') : copy(`Selesaikan 1 sesi ${dailyGame.title[lang]} hari ini dan raih +${todayChallenge.rewardXp} XP bonus.`, `Complete 1 ${dailyGame.title[lang]} session today and earn +${todayChallenge.rewardXp} bonus XP.`)}</p></div></div>
        <div className="home-daily-reward"><span><Icon name="bolt" size={15}/>{copy('Streak', 'Streak')} <strong>{currentStreak}</strong></span><span><Icon name="spark" size={15}/><strong>+{todayChallenge.rewardXp} XP</strong></span></div>
        <button className={`ba-button ${dailyCompleted ? 'outline' : 'primary'}`} onClick={() => onSelectGame(dailyCompleted ? 'daily' : dailyGame.id)}>{dailyCompleted ? copy('Lihat Daily', 'View Daily') : copy('Mulai sekarang', 'Start now')}<Icon name="arrow" size={15}/></button>
        <button className="home-level-mini" onClick={() => onSelectGame('profile')}><span className="profile-avatar"><Icon name="user" size={16}/></span><span><small>{profile.name || copy('Pemain Lokal', 'Local Player')}</small><strong>Lv. {levelInfo.level} · {levelInfo.rank[lang]}</strong></span><i><b style={{ width:`${levelInfo.progress}%` }}/></i></button>
      </section>
      <div className="category-strip">{['math','logic','memory','strategy'].map((key,i) => <button key={key} onClick={() => { setCategory(category === key ? 'all' : key); catalog.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }} className={category === key ? 'selected' : ''} aria-pressed={category === key}><span className={`category-icon category-${key}`}><Icon name={['bolt','cube','brain','dice'][i]} size={21}/></span><span><strong>{CATEGORIES[key][lang]}</strong><small>{[copy('Kecepatan berhitung', 'Fast thinking'),copy('Ketajaman analisis', 'Clear reasoning'),copy('Kekuatan ingatan', 'Stronger recall'),copy('Langkah penuh taktik', 'Smarter moves')][i]}</small></span><Icon name="chevron" size={16}/></button>)}</div>
    </>}
    <section className="catalog-section" ref={catalog} id="game-catalog" aria-labelledby="catalog-title">
      <div className="section-heading"><div><h2 id="catalog-title">{favoriteView ? copy('Koleksi favorit', 'Your collection') : copy('Pilih arena bermainmu', 'Choose your arena')}<span className="count-badge">{baseGames.length}</span></h2><p>{copy('Tantangan berbeda. Satu tujuan: jadi lebih tajam.', 'Different challenges. One goal: a sharper you.')}</p></div><button className="text-button random-button" onClick={() => { const pool = filtered.length ? filtered : GAMES; onSelectGame(pool[Math.floor(Math.random()*pool.length)].id); }}><Icon name="shuffle" size={16}/>{copy('Pilihkan untukku', 'Surprise me')}</button></div>
      <div className="catalog-toolbar"><div className="season-tabs" role="group" aria-label={copy('Filter musim', 'Filter by season')}>{['all', ...[...new Set(GAMES.map(game => String(game.season)))].sort((a,b)=>Number(a)-Number(b))].map(s => <button key={s} className={season === s ? 'active' : ''} aria-pressed={season === s} onClick={() => setSeason(s)}>{s === 'all' ? copy('Semua game', 'All games') : `${copy('Musim', 'Season')} ${s}`}<span>{s === 'all' ? baseGames.length : baseGames.filter(g => g.season === Number(s)).length}</span></button>)}</div><div className="catalog-controls"><label className="catalog-search"><Icon name="search" size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder={copy('Cari game...', 'Find a game...')} aria-label={copy('Cari dalam katalog game', 'Search game catalog')}/>{query && <button onClick={() => setQuery('')} aria-label={copy('Hapus pencarian', 'Clear search')}><Icon name="close" size={14}/></button>}</label><label className="category-select"><select value={category} onChange={e => setCategory(e.target.value)} aria-label={copy('Kategori permainan', 'Game category')}>{Object.entries(CATEGORIES).map(([id,name]) => <option value={id} key={id}>{name[lang]}</option>)}</select><Icon name="down" size={14}/></label></div></div>
      <p className="sr-only" role="status">{filtered.length} {copy('permainan ditemukan', 'games found')}</p>
      {filtered.length ? <div className="game-grid">{filtered.map(game => <GameCard key={game.id} game={game} onSelectGame={onSelectGame}/>)}</div> : <div className="empty-state"><span className="empty-icon"><Icon name={favoriteView && !favorites.length ? 'star' : 'search'} size={30}/></span><h3>{favoriteView && !favorites.length ? copy('Favoritmu menunggu di sini.', 'Your favorites belong here.') : copy('Belum ada yang cocok.', 'No matches just yet.')}</h3><p>{favoriteView && !favorites.length ? copy('Tekan ikon bintang pada game yang kamu suka untuk menyimpannya.', 'Tap the star on a game you like to add it to your collection.') : copy('Coba kata kunci lain atau hapus filter yang aktif.', 'Try another search or clear your active filters.')}</p><button className="ba-button primary" onClick={() => { setQuery(''); setCategory('all'); setSeason('all'); if (favoriteView && !favorites.length) onSelectGame('games'); }}>{favoriteView && !favorites.length ? copy('Temukan game', 'Discover games') : copy('Reset filter', 'Reset filters')}<Icon name="arrow" size={16}/></button></div>}
    </section>
    {home && recent.length > 0 && <section className="recent-section"><div className="section-heading"><h2>{copy('Terakhir kamu buka', 'Recently opened')}</h2><button className="text-button" onClick={() => onSelectGame('activity')}>{copy('Lihat aktivitas', 'View activity')}<Icon name="arrow" size={15}/></button></div><div className="recent-grid">{recent.map(game => <button className={`recent-card color-${game.color}`} key={game.id} onClick={() => onSelectGame(game.id)}><span className="mini-game-icon"><Icon name={game.icon}/></span><span><strong>{game.title[lang]}</strong><small>{copy('Buka sesi baru', 'Start a new session')}</small></span><Icon name="arrow" size={17}/></button>)}</div></section>}
    <section className="guide-banner"><span className="guide-banner-icon"><Icon name="book" size={28}/></span><div><span className="eyebrow">{copy('SEDIKIT STRATEGI, BANYAK KEMAJUAN', 'A LITTLE STRATEGY GOES A LONG WAY')}</span><h2>{copy('Main lebih cerdas, bukan lebih keras.', 'Play smarter, not harder.')}</h2><p>{copy('Pelajari aturan dan trik untuk setiap permainan sebelum masuk arena.', 'Learn the rules and discover a smarter approach to every game.')}</p></div><button className="ba-button outline" onClick={() => onSelectGame('guides')}>{copy('Buka panduan', 'Explore guides')}<Icon name="arrow" size={16}/></button></section>
  </div>;
}
