import React, { useMemo, useState } from 'react';
import { useLanguage } from '../context/LanguageContext.jsx';
import Icon from '../components/Icon.jsx';
import { createLocalProfile, deleteLocalProfile, ensureLocalProfiles, renameLocalProfile, saveActiveLocalProfile, switchLocalProfile } from '../utils/localProfiles.js';

export default function LocalProfiles(){
  const {lang}=useLanguage(); const copy=(id,en)=>lang==='id'?id:en;
  const [state,setState]=useState(()=>ensureLocalProfiles()); const [name,setName]=useState(''); const [error,setError]=useState('');
  const active=useMemo(()=>state.profiles.find(item=>item.id===state.activeId),[state]);
  const refresh=()=>{try{saveActiveLocalProfile();setState(ensureLocalProfiles());}catch{}}
  const create=()=>{setError('');try{const item=createLocalProfile(name||copy('Pemain Baru','New Player'));setName('');setState(ensureLocalProfiles());return item;}catch(e){setError(e.message==='profile-limit'?copy('Maksimal 6 profil lokal.','Maximum 6 local profiles.'):copy('Profil tidak dapat dibuat.','Could not create profile.'));}}
  const switchTo=id=>{if(id===state.activeId)return;try{switchLocalProfile(id);location.reload();}catch{setError(copy('Profil tidak dapat dibuka.','Could not open profile.'));}}
  const rename=(id,current)=>{const next=prompt(copy('Nama profil baru','New profile name'),current);if(next){renameLocalProfile(id,next);if(id===state.activeId)location.reload();else refresh();}}
  const remove=id=>{if(!confirm(copy('Hapus profil ini? Backup slot profil juga akan dihapus.','Delete this profile? Its profile slot backup will also be removed.')))return;try{deleteLocalProfile(id);refresh();}catch{setError(copy('Profil aktif tidak dapat dihapus. Pindah profil terlebih dahulu.','The active profile cannot be deleted. Switch profiles first.'));}}
  return <div className="meta-page local-profiles-page"><div className="page-heading"><div><span className="eyebrow">MULTI LOCAL PROFILE</span><h1>{copy('Satu perangkat, beberapa pemain.','One device, multiple players.')}</h1><p className="page-intro">{copy('Setiap profil mempunyai XP, Rank, statistik, history, favorit, dan pengaturan progresnya sendiri.','Each profile keeps its own XP, Rank, statistics, history, favorites, and progression settings.')}</p></div></div>
    <section className="profile-manager-hero"><div><Icon name="users" size={26}/><span><small>{copy('PROFIL AKTIF','ACTIVE PROFILE')}</small><strong>{active?.name||'—'}</strong><p>{copy('Pergantian profil menyimpan progress aktif sebelum memuat slot pemain lain.','Switching profiles saves the active progress before loading another player slot.')}</p></span></div><button className="ba-button outline" onClick={refresh}><Icon name="refresh" size={15}/>{copy('Sinkronkan slot','Sync slot')}</button></section>
    <section className="profile-create-card"><div><span className="eyebrow">{copy('TAMBAH PROFIL','ADD PROFILE')}</span><h2>{copy('Buat pemain lokal baru','Create a new local player')}</h2></div><div className="profile-create-form"><input value={name} maxLength={24} onChange={e=>setName(e.target.value)} placeholder={copy('Nama pemain...','Player name...')}/><button className="ba-button primary" onClick={create}><Icon name="user" size={15}/>{copy('Buat profil','Create profile')}</button></div></section>
    {error&&<p className="settings-error" role="alert">{error}</p>}
    <div className="local-profile-grid">{state.profiles.map(item=><article key={item.id} className={item.id===state.activeId?'active':''}><header><span className="local-profile-card-avatar"><Icon name="user" size={21}/></span><div><small>{item.id===state.activeId?copy('AKTIF','ACTIVE'):copy('PROFIL LOKAL','LOCAL PROFILE')}</small><h2>{item.name}</h2></div>{item.id===state.activeId&&<span className="status-pill active"><Icon name="check" size={11}/>{copy('Digunakan','In use')}</span>}</header><p>{copy('Dibuat','Created')}: {new Date(item.createdAt).toLocaleDateString(lang==='id'?'id-ID':'en-US')}</p><p>{copy('Terakhir aktif','Last active')}: {item.lastActiveAt?new Date(item.lastActiveAt).toLocaleString(lang==='id'?'id-ID':'en-US'):copy('Belum pernah','Never')}</p><footer>{item.id!==state.activeId&&<button className="ba-button primary" onClick={()=>switchTo(item.id)}>{copy('Gunakan profil','Use profile')}<Icon name="arrow" size={14}/></button>}<button className="ba-button outline" onClick={()=>rename(item.id,item.name)}>{copy('Ubah nama','Rename')}</button>{item.id!==state.activeId&&<button className="icon-button danger" onClick={()=>remove(item.id)} aria-label={copy('Hapus profil','Delete profile')}><Icon name="trash" size={15}/></button>}</footer></article>)}</div>
  </div>;
}
