import React, { useEffect, useMemo, useState } from 'react';
import { useLanguage } from '../context/LanguageContext.jsx';
import { useArena } from '../context/ArenaContext.jsx';
import { gameById } from '../data/games.js';
import { formatDuration } from '../utils/competitive.js';
import { brainCoachReview } from '../utils/coachV2.js';
import { integrityLabel } from '../utils/integrity.js';
import Icon from '../components/Icon.jsx';

const iconForAction = type => type==='key'?'keyboard':type==='hint'?'brain':type==='system'?'shield':'cursor';
const toneForAction = action => action?.type==='hint'?'hint':action?.type==='system'?'system':/(wrong|salah|error|miss|gagal)/i.test(action?.label||'')?'warn':'normal';

export default function ReplayViewer({ onNavigate }) {
  const { lang }=useLanguage(); const { matches,selectedReplayId }=useArena();
  const copy=(id,en)=>lang==='id'?id:en;
  const match=useMemo(()=>matches.find(item=>item.id===selectedReplayId)||matches[0]||null,[matches,selectedReplayId]);
  const [playing,setPlaying]=useState(false); const [speed,setSpeed]=useState(1); const [index,setIndex]=useState(0);
  useEffect(()=>{setPlaying(false);setIndex(0);setSpeed(1);},[match?.id]);
  const actions=match?.replay||[];
  const duration=Math.max(Number(match?.durationMs)||0,Number(actions.at(-1)?.t)||0,1);
  useEffect(()=>{ if(!playing||!actions.length) return; if(index>=actions.length-1){setPlaying(false);return;} const current=actions[index]; const next=actions[index+1]; const wait=Math.max(70,Math.min(1300,((next.t-current.t)||350)/speed)); const timer=setTimeout(()=>setIndex(v=>Math.min(v+1,actions.length-1)),wait); return()=>clearTimeout(timer); },[playing,index,speed,actions]);
  if(!match) return <div className="empty-state"><Icon name="play" size={36}/><h2>{copy('Belum ada replay','No replay yet')}</h2><button className="ba-button primary" onClick={()=>onNavigate('games')}>{copy('Mainkan game','Play a game')}</button></div>;
  const game=gameById(match.gameId); const current=actions[index]; const currentTime=current?.t||0;
  const coach=brainCoachReview(match,matches,lang); const integrity=integrityLabel(match.integrity,lang);
  const seekTo=time=>{ if(!actions.length){setIndex(0);return;} let best=0; for(let i=0;i<actions.length;i+=1){if(actions[i].t<=time)best=i;else break;} setIndex(best); setPlaying(false); };
  const skip=delta=>seekTo(Math.max(0,Math.min(duration,currentTime+delta)));
  const markers=actions.map((action,i)=>({action,i,left:Math.max(0,Math.min(100,(Number(action.t||0)/duration)*100)),tone:toneForAction(action)})).filter(item=>item.tone!=='normal');
  return <div className="competitive-page replay-page replay-v2-page"><section className="competitive-hero"><div><span className="section-eyebrow"><Icon name="play" size={15}/>{copy('REPLAY v2','REPLAY v2')}</span><h1>{game?.title?.[lang]}</h1><p>{copy('Scrub timeline, lompat 5 detik, putar lambat atau cepat, dan lihat marker Brain Coach, perubahan fokus, serta momen penting sesi.','Scrub the timeline, jump 5 seconds, play slow or fast, and inspect Brain Coach, focus-change, and key session markers.')}</p></div><div className="hero-stat"><span>{copy('PERFORMA','PERFORMANCE')}</span><strong>{match.grade}</strong><small>{match.performance}/100</small></div></section>
    <section className="replay-shell replay-v2-shell"><div className="replay-stage"><div className="replay-meta"><span><Icon name="hash" size={14}/>{match.challengeCode}</span><span><Icon name="clock" size={14}/>{formatDuration(match.durationMs)}</span><span><Icon name="shield" size={14}/>{match.mode==='ranked'?'Ranked':'Practice'}</span>{match.mode==='ranked'&&<span className={`replay-integrity ${integrity.status}`}><Icon name={integrity.status==='clean'?'check':'refresh'} size={13}/>{integrity.label}</span>}</div>
      <div className="replay-focus"><span>{copy('AKSI SAAT INI','CURRENT ACTION')}</span><strong>{current?.label||copy('Tidak ada input yang terekam','No recorded input')}</strong><small>{formatDuration(currentTime)} · {current?.type||'—'}</small></div>
      <div className="replay-scrubber"><div className="replay-marker-track">{markers.map(item=><button key={`${item.i}-${item.left}`} className={`replay-marker marker-${item.tone}`} style={{left:`${item.left}%`}} onClick={()=>{setIndex(item.i);setPlaying(false);}} title={item.action.label}><Icon name={iconForAction(item.action.type)} size={10}/></button>)}</div><input aria-label={copy('Timeline replay','Replay timeline')} type="range" min="0" max={duration} step="100" value={currentTime} onChange={e=>seekTo(Number(e.target.value))}/><div className="replay-time-row"><span>{formatDuration(currentTime)}</span><span>{formatDuration(duration)}</span></div></div>
      <div className="replay-controls replay-controls-v2"><button onClick={()=>skip(-5000)} disabled={!actions.length}><Icon name="back" size={15}/><span>5s</span></button><button onClick={()=>setIndex(Math.max(0,index-1))} disabled={!index}><Icon name="back" size={16}/></button><button className="replay-play" onClick={()=>setPlaying(v=>!v)} disabled={!actions.length}><Icon name={playing?'pause':'play'} size={18}/>{playing?copy('Jeda','Pause'):copy('Putar','Play')}</button><button onClick={()=>setIndex(Math.min(actions.length-1,index+1))} disabled={!actions.length||index>=actions.length-1}><Icon name="arrow" size={16}/></button><button onClick={()=>skip(5000)} disabled={!actions.length}><span>5s</span><Icon name="arrow" size={15}/></button><div className="replay-speeds">{[0.5,1,2,4].map(v=><button key={v} className={speed===v?'active':''} onClick={()=>setSpeed(v)}>{v}×</button>)}</div></div>
      {coach&&<section className="replay-coach-v2"><header><span><Icon name="brain" size={18}/></span><div><small>BRAIN COACH v2</small><strong>{copy('Review setelah permainan','Post-game review')}</strong></div></header><p className="coach-focus"><b>{copy('Fokus berikutnya:','Next focus:')}</b> {coach.focus}</p>{coach.notes.length>0&&<div>{coach.notes.map((note,i)=><p key={i}><Icon name="spark" size={13}/>{note}</p>)}</div>}</section>}
    </div><aside className="replay-timeline"><div className="replay-timeline-head"><strong>{copy('Timeline aksi','Action timeline')}</strong><span>{actions.length} {copy('aksi','actions')}</span></div>{actions.length?<div>{actions.map((action,i)=><button key={`${action.t}-${i}`} className={`${i===index?'active':''} timeline-${toneForAction(action)}`} onClick={()=>{setIndex(i);setPlaying(false);}}><span>{formatDuration(action.t)}</span><i className={`action-${action.type}`}><Icon name={iconForAction(action.type)} size={13}/></i><strong>{action.label}</strong></button>)}</div>:<p className="replay-empty">{copy('Sesi ini selesai sebelum recorder menangkap input.','This session ended before the recorder captured input.')}</p>}</aside></section><div className="replay-footer-actions"><button className="ba-button primary" onClick={()=>onNavigate('share-result')}><Icon name="send" size={15}/>{copy('Buat Result Card','Create Result Card')}</button><button className="ba-button outline" onClick={()=>onNavigate('history')}><Icon name="back" size={15}/>{copy('Kembali ke Match History','Back to Match History')}</button></div>
  </div>;
}
