import React, { useEffect, useMemo, useState } from 'react';
import { useLanguage } from '../context/LanguageContext.jsx';
import { useArena } from '../context/ArenaContext.jsx';
import { gameById } from '../data/games.js';
import { formatDuration } from '../utils/competitive.js';
import Icon from '../components/Icon.jsx';

export default function ReplayViewer({ onNavigate }) {
  const { lang }=useLanguage(); const { matches,selectedReplayId }=useArena();
  const copy=(id,en)=>lang==='id'?id:en;
  const match=useMemo(()=>matches.find(item=>item.id===selectedReplayId)||matches[0]||null,[matches,selectedReplayId]);
  const [playing,setPlaying]=useState(false); const [speed,setSpeed]=useState(1); const [index,setIndex]=useState(0);
  useEffect(()=>{setPlaying(false);setIndex(0);},[match?.id]);
  useEffect(()=>{ if(!playing||!match?.replay?.length) return; if(index>=match.replay.length-1){setPlaying(false);return;} const current=match.replay[index]; const next=match.replay[index+1]; const wait=Math.max(120,Math.min(1200,((next.t-current.t)||400)/speed)); const timer=setTimeout(()=>setIndex(v=>Math.min(v+1,match.replay.length-1)),wait); return()=>clearTimeout(timer); },[playing,index,speed,match]);
  if(!match) return <div className="empty-state"><Icon name="play" size={36}/><h2>{copy('Belum ada replay','No replay yet')}</h2><button className="ba-button primary" onClick={()=>onNavigate('games')}>{copy('Mainkan game','Play a game')}</button></div>;
  const game=gameById(match.gameId); const actions=match.replay||[]; const current=actions[index];
  return <div className="competitive-page replay-page"><section className="competitive-hero"><div><span className="section-eyebrow"><Icon name="play" size={15}/>{copy('ACTION REPLAY','ACTION REPLAY')}</span><h1>{game?.title?.[lang]}</h1><p>{copy('Replay menampilkan timeline input yang terekam selama sesi: tombol, arah keyboard, dan penggunaan Brain Coach. Ini adalah replay aksi, bukan video layar.','Replay shows the recorded input timeline from the session: buttons, keyboard directions, and Brain Coach usage. This is an action replay, not a screen recording.')}</p></div><div className="hero-stat"><span>{copy('PERFORMA','PERFORMANCE')}</span><strong>{match.grade}</strong><small>{match.performance}/100</small></div></section>
    <section className="replay-shell"><div className="replay-stage"><div className="replay-meta"><span><Icon name="hash" size={14}/>{match.challengeCode}</span><span><Icon name="clock" size={14}/>{formatDuration(match.durationMs)}</span><span><Icon name="shield" size={14}/>{match.mode==='ranked'?'Ranked':'Practice'}</span></div><div className="replay-focus"><span>{copy('AKSI SAAT INI','CURRENT ACTION')}</span><strong>{current?.label||copy('Tidak ada input yang terekam','No recorded input')}</strong><small>{current?formatDuration(current.t):'00:00'} · {current?.type||'—'}</small></div><div className="replay-progress"><i style={{width:`${actions.length>1?(index/(actions.length-1))*100:0}%`}}/></div><div className="replay-controls"><button onClick={()=>setIndex(Math.max(0,index-1))} disabled={!index}><Icon name="back" size={16}/></button><button className="replay-play" onClick={()=>setPlaying(v=>!v)} disabled={!actions.length}><Icon name={playing?'pause':'play'} size={18}/>{playing?copy('Jeda','Pause'):copy('Putar','Play')}</button><button onClick={()=>setIndex(Math.min(actions.length-1,index+1))} disabled={!actions.length||index>=actions.length-1}><Icon name="arrow" size={16}/></button><div className="replay-speeds">{[1,2,4].map(v=><button key={v} className={speed===v?'active':''} onClick={()=>setSpeed(v)}>{v}×</button>)}</div></div></div><aside className="replay-timeline"><div className="replay-timeline-head"><strong>{copy('Timeline aksi','Action timeline')}</strong><span>{actions.length} {copy('aksi','actions')}</span></div>{actions.length?<div>{actions.map((action,i)=><button key={`${action.t}-${i}`} className={i===index?'active':''} onClick={()=>{setIndex(i);setPlaying(false);}}><span>{formatDuration(action.t)}</span><i className={`action-${action.type}`}><Icon name={action.type==='key'?'keyboard':action.type==='hint'?'brain':'cursor'} size={13}/></i><strong>{action.label}</strong></button>)}</div>:<p className="replay-empty">{copy('Sesi ini selesai sebelum recorder menangkap input. Replay baru akan lebih lengkap.','This session ended before the recorder captured input. New replays will be more complete.')}</p>}</aside></section><button className="ba-button outline" onClick={()=>onNavigate('history')}><Icon name="back" size={15}/>{copy('Kembali ke Match History','Back to Match History')}</button>
  </div>;
}
