import React, { useRef, useState } from 'react';
import Icon from '../components/Icon.jsx';
import { useArena } from '../context/ArenaContext.jsx';
import { useLanguage } from '../context/LanguageContext.jsx';
import { createProgressBackup, importProgressBackup } from '../utils/backup.js';
import { DATA_SCHEMA_VERSION, dataSchemaVersion } from '../utils/migration.js';

export default function Settings() {
  const {lang}=useLanguage(); const copy=(id,en)=>lang==='en'?en:id; const {accessibility,updateAccessibility,setNotice}=useArena();
  const fileRef=useRef(null); const [replace,setReplace]=useState(false); const [error,setError]=useState('');
  const schemaVersion=dataSchemaVersion();
  const download=()=>{try{const payload=JSON.stringify(createProgressBackup(),null,2);const blob=new Blob([payload],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`brain-arena-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);setNotice(copy('Backup berhasil dibuat','Backup created'));}catch{setError(copy('Backup tidak dapat dibuat di browser ini.','Could not create a backup in this browser.'));}};
  const upload=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setError('');try{const text=await file.text();const raw=JSON.parse(text);const count=importProgressBackup(raw,window.localStorage,replace);setNotice(copy(`${count} data berhasil diimpor`,`${count} data entries imported`));setTimeout(()=>window.location.reload(),550);}catch{setError(copy('File backup tidak valid atau rusak.','The backup file is invalid or corrupted.'));}};
  const toggle=(key,label)=> <label className="setting-toggle"><span><strong>{label[0]}</strong><small>{label[1]}</small></span><input type="checkbox" checked={accessibility[key]} onChange={e=>updateAccessibility(key,e.target.checked)}/><i/></label>;
  return <div className="meta-page settings-page"><div className="page-heading"><div><span className="eyebrow">SETTINGS & DATA</span><h1>{copy('Atur pengalaman bermainmu.','Tune your playing experience.')}</h1><p className="page-intro">{copy('Aksesibilitas dan backup berjalan sepenuhnya di perangkat ini.','Accessibility and backups stay entirely on this device.')}</p></div></div>
    <div className="settings-grid"><section className="settings-panel"><div className="settings-title"><span><Icon name="sliders" size={20}/></span><div><h2>{copy('Aksesibilitas','Accessibility')}</h2><p>{copy('Sesuaikan tampilan tanpa mengubah gameplay.','Adjust presentation without changing gameplay.')}</p></div></div><label className="theme-select"><span>{copy('Tema','Theme')}</span><select value={accessibility.theme} onChange={e=>updateAccessibility('theme',e.target.value)}><option value="system">{copy('Ikuti sistem','System')}</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label className="theme-select"><span>{copy('Mode penglihatan warna','Color vision')}</span><select value={accessibility.colorVision||'default'} onChange={e=>updateAccessibility('colorVision',e.target.value)}><option value="default">Default</option><option value="protanopia">Protanopia</option><option value="deuteranopia">Deuteranopia</option><option value="tritanopia">Tritanopia</option><option value="monochrome">Monochrome</option></select></label>{toggle('reducedMotion',[copy('Kurangi animasi','Reduce motion'),copy('Meminimalkan transisi dan gerakan dekoratif.','Minimizes transitions and decorative movement.')])}{toggle('highContrast',[copy('Kontras tinggi','High contrast'),copy('Mempertegas batas, teks, dan fokus kontrol.','Strengthens borders, text, and control focus.')])}{toggle('largeText',[copy('Teks lebih besar','Larger text'),copy('Meningkatkan ukuran teks antarmuka utama.','Increases primary interface text size.')])}{toggle('enhancedFocus',[copy('Focus ring diperkuat','Enhanced focus ring'),copy('Membuat posisi keyboard focus lebih mudah dilihat.','Makes keyboard focus easier to see.')])}{toggle('screenReaderHints',[copy('Hint screen reader','Screen reader hints'),copy('Menambahkan konteks aksesibel pada kontrol utama.','Adds accessible context to key controls.')])}{toggle('disableTimerPressure',[copy('Kurangi tekanan timer','Reduce timer pressure'),copy('Menyamarkan penekanan visual timer; aturan game tetap sama.','Reduces timer emphasis; game rules remain unchanged.')])}</section>
      <section className="settings-panel"><div className="settings-title"><span><Icon name="download" size={20}/></span><div><h2>{copy('Backup progress','Progress backup')}</h2><p>{copy('Pindahkan progres antarbrowser sebelum Cloud Save tersedia.','Move progress between browsers before Cloud Save arrives.')}</p></div></div><div className="data-schema-status"><span><Icon name="refresh" size={15}/></span><div><small>{copy('VERSI DATA','DATA VERSION')}</small><strong>Schema v{schemaVersion} / v{DATA_SCHEMA_VERSION}</strong><p>{copy('v1.15 memigrasikan preferensi dan progres lama secara otomatis tanpa mereset XP, rank, record, atau profil.','v1.15 automatically migrates older preferences and progress without resetting XP, rank, records, or profile.')}</p></div></div><div className="backup-actions"><button className="ba-button primary" onClick={download}><Icon name="download" size={16}/>{copy('Export progress','Export progress')}</button><button className="ba-button outline" onClick={()=>fileRef.current?.click()}><Icon name="refresh" size={16}/>{copy('Import backup','Import backup')}</button><input ref={fileRef} className="sr-only" type="file" accept="application/json,.json" onChange={upload}/></div><label className="backup-replace"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/><span><strong>{copy('Ganti data lokal saat import','Replace local data on import')}</strong><small>{copy('Jika mati, data backup akan digabung dengan data yang sudah ada.','When off, backup values are merged into your existing local data.')}</small></span></label>{error&&<p className="settings-error" role="alert">{error}</p>}<div className="backup-note"><Icon name="shield" size={18}/><p>{copy('File backup hanya berisi data Brain Arena yang tersimpan lokal. Periksa file sebelum membagikannya.','The backup contains only locally stored Brain Arena data. Review it before sharing.')}</p></div></section></div>
  </div>;
}
