import React, { useMemo, useState } from 'react';
import { useLanguage } from '../context/LanguageContext.jsx';
import { useArena } from '../context/ArenaContext.jsx';
import { GAMES, gameById } from '../data/games.js';
import Icon from '../components/Icon.jsx';

const KEY='ba_showcase_v1';
const load=()=>{try{return {featuredGame:null,featuredMatch:null,showRank:true,showStreak:true,showMastery:true,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{featuredGame:null,featuredMatch:null,showRank:true,showStreak:true,showMastery:true}}};
export default function Showcase({onNavigate}){
 const {lang}=useLanguage();const copy=(id,en)=>lang==='id'?id:en;const {profile,levelInfo,rankInfo,currentStreak,selectedBadge,avatarOption,frameOption,titleOption,matches,masteryForGame}=useArena();
 const [config,setConfig]=useState(load);const save=(field,value)=>setConfig(prev=>{const next={...prev,[field]:value};localStorage.setItem(KEY,JSON.stringify(next));return next;});
 const topGame=useMemo(()=>{const ranked=GAMES.map(game=>({game,completions:Number(profile.perGame?.[game.id]?.completions)||0})).sort((a,b)=>b.completions-a.completions);return gameById(config.featuredGame)||ranked[0]?.game||GAMES[0];},[config.featuredGame,profile.perGame]);
 const featuredMatch=matches.find(item=>item.id===config.featuredMatch)||matches.find(item=>item.gameId===topGame.id)||matches[0];const mastery=masteryForGame(topGame.id);
 return <div className="meta-page showcase-page"><div className="page-heading"><div><span className="eyebrow">PLAYER SHOWCASE</span><h1>{copy('Tampilkan progres yang paling berarti.','Show the progress that matters most.')}</h1><p className="page-intro">{copy('Pilih game dan pencapaian yang ingin ditonjolkan pada kartu profil lokalmu.','Choose the game and achievements you want featured on your local player card.')}</p></div></div>
 <section className="showcase-card"><div className="showcase-banner"><div className={`profile-avatar-large frame-${frameOption.id}`}><Icon name={avatarOption.icon} size={31}/></div><div><span className="eyebrow">BRAIN ARENA PLAYER</span><h2>{profile.name||copy('Pemain Lokal','Local Player')}</h2><p>{titleOption.title[lang]} · Lv. {levelInfo.level}</p></div>{selectedBadge&&<span className="showcase-badge"><Icon name={selectedBadge.icon} size={18}/>{selectedBadge.title[lang]}</span>}</div><div className="showcase-stats">{config.showRank&&<div><small>ARENA RANK</small><strong>{rankInfo.tier.title[lang]}</strong><span>{rankInfo.rating.toLocaleString()} AR</span></div>}{config.showStreak&&<div><small>STREAK</small><strong>{currentStreak}</strong><span>{copy('hari','days')}</span></div>}{config.showMastery&&<div><small>MASTERY</small><strong>Lv. {mastery.level}</strong><span>{topGame.title[lang]}</span></div>}<div><small>{copy('SESI','SESSIONS')}</small><strong>{profile.completions}</strong><span>{profile.xp.toLocaleString()} XP</span></div></div>{featuredMatch&&<div className="showcase-best"><span className={`mini-game-icon color-${gameById(featuredMatch.gameId)?.color}`}><Icon name={gameById(featuredMatch.gameId)?.icon||'trophy'} size={18}/></span><div><small>{copy('HASIL PILIHAN','FEATURED RESULT')}</small><strong>{gameById(featuredMatch.gameId)?.title[lang]} · Grade {featuredMatch.grade}</strong><p>{featuredMatch.performance}/100 · {featuredMatch.mode==='ranked'?'Ranked':'Practice'}</p></div><button className="text-button" onClick={()=>onNavigate('history')}>{copy('Lihat riwayat','View history')}<Icon name="arrow" size={13}/></button></div>}</section>
 <section className="showcase-config"><h2>{copy('Atur showcase','Customize showcase')}</h2><label><span>{copy('Game unggulan','Featured game')}</span><select value={topGame.id} onChange={e=>save('featuredGame',e.target.value)}>{GAMES.map(g=><option key={g.id} value={g.id}>{g.title[lang]}</option>)}</select></label><label><span>{copy('Hasil unggulan','Featured result')}</span><select value={featuredMatch?.id||''} onChange={e=>save('featuredMatch',e.target.value)}><option value="">{copy('Otomatis','Automatic')}</option>{matches.slice(0,40).map(m=><option key={m.id} value={m.id}>{gameById(m.gameId)?.title[lang]} · {m.grade} · {m.performance}</option>)}</select></label>{[['showRank',copy('Tampilkan Arena Rank','Show Arena Rank')],['showStreak',copy('Tampilkan streak','Show streak')],['showMastery',copy('Tampilkan mastery','Show mastery')]].map(([key,label])=><label className="showcase-toggle" key={key}><input type="checkbox" checked={config[key]} onChange={e=>save(key,e.target.checked)}/><span>{label}</span></label>)}</section>
 </div>;
}
