import React, { useMemo, useState } from 'react';
import { useLanguage } from '../context/LanguageContext.jsx';
import { useArena } from '../context/ArenaContext.jsx';
import { CATEGORIES, GAMES } from '../data/games.js';
import { buildAdvancedStatistics } from '../utils/statistics.js';
import Icon from '../components/Icon.jsx';
import { buildPerformanceAnalytics } from '../utils/performanceAnalytics.js';
import { formatDuration } from '../utils/competitive.js';

const dayLabel=(key,lang)=>new Intl.DateTimeFormat(lang==='id'?'id-ID':'en-US',{weekday:'short'}).format(new Date(`${key}T12:00:00`));

export default function Statistics({onNavigate}) {
  const {lang}=useLanguage();
  const {profile,daily,rankInfo,achievements,matches}=useArena();
  const copy=(id,en)=>lang==='id'?id:en;
  const stats=useMemo(()=>buildAdvancedStatistics(profile,daily),[profile,daily]);
  const [range,setRange]=useState('30');
  const performance=useMemo(()=>buildPerformanceAnalytics(matches,range),[matches,range]);
  const maxSessions=Math.max(1,...stats.last7.map(day=>day.sessions));
  const maxXp=Math.max(1,...stats.last7.map(day=>day.xp));
  const totalCategory=Math.max(1,stats.categoryStats.reduce((sum,item)=>sum+item.completions,0));
  return <div className="progression-page statistics-page">
    <section className="progression-hero statistics-hero"><div><span className="eyebrow"><Icon name="activity" size={14}/>{copy('ADVANCED STATISTICS','ADVANCED STATISTICS')}</span><h1>{copy('Lihat cara kamu berkembang.','See how your play is evolving.')}</h1><p>{copy('Statistik dihitung dari sesi dan XP yang tersimpan di browser ini: tren 7 hari, distribusi kategori, konsistensi, eksplorasi game, dan performa setiap arena.','Statistics are calculated from sessions and XP stored in this browser: 7-day trends, category distribution, consistency, game exploration, and per-arena performance.')}</p></div><div className="progression-hero-stat"><small>{copy('ARENA RATING','ARENA RATING')}</small><strong>{rankInfo.rating.toLocaleString()}</strong><span>{rankInfo.tier.title[lang]} · {Object.keys(achievements.unlocked||{}).length} {copy('badge','badges')}</span><i><b style={{width:`${rankInfo.progress}%`}}/></i></div></section>

    <section className="analytics-v2-toolbar"><div><span className="eyebrow">PERFORMANCE ANALYTICS v2</span><h2>{copy('Analisis hasil kompetitif','Competitive performance analysis')}</h2></div><div className="analytics-range">{[['7','7 Hari','7 Days'],['30','30 Hari','30 Days'],['season','Season','Season'],['all','All Time','All Time']].map(([id,idLabel,enLabel])=><button key={id} className={range===id?'active':''} onClick={()=>setRange(id)}>{copy(idLabel,enLabel)}</button>)}</div></section>
    <section className="analytics-v2-kpis"><article><small>{copy('MATCH','MATCHES')}</small><strong>{performance.total}</strong><span>{performance.ranked} Ranked</span></article><article><small>{copy('WIN RATE','WIN RATE')}</small><strong>{performance.winRate}%</strong><span>{copy('sesi berhasil','successful sessions')}</span></article><article><small>{copy('AVG GRADE','AVG GRADE')}</small><strong>{performance.avgGrade}</strong><span>{performance.avgPerformance}/100</span></article><article><small>{copy('PB IMPROVED','PB IMPROVED')}</small><strong>{performance.pbImproved}</strong><span>{copy('rekor baru','new records')}</span></article><article><small>RANKED RP</small><strong>{performance.rp>=0?'+':''}{performance.rp}</strong><span>{performance.hints} hint</span></article></section>
    {performance.trend.length>0&&<section className="stats-panel analytics-trend-panel"><header><div><span className="eyebrow">TREND</span><h2>{copy('Tren performa','Performance trend')}</h2></div><strong>{performance.avgPerformance}/100</strong></header><div className="analytics-trend-chart">{performance.trend.map(day=><div key={day.dateKey}><i style={{height:`${Math.max(4,day.performance)}%`}}/><span>{day.dateKey.slice(5)}</span><small>{day.performance}</small></div>)}</div></section>}
    <section className="statistics-kpis"><article><span><Icon name="gamepad" size={20}/></span><small>{copy('TOTAL SESI','TOTAL SESSIONS')}</small><strong>{stats.totalSessions}</strong><p>{copy(`${stats.avgSessionsPerActiveDay} sesi / hari aktif`,`${stats.avgSessionsPerActiveDay} sessions / active day`)}</p></article><article><span><Icon name="bolt" size={20}/></span><small>{copy('XP / SESI','XP / SESSION')}</small><strong>{stats.avgXpPerSession}</strong><p>{copy(`${stats.weekXp} XP dalam 7 hari`,` ${stats.weekXp} XP in 7 days`)}</p></article><article><span><Icon name="grid" size={20}/></span><small>{copy('EKSPLORASI','EXPLORATION')}</small><strong>{stats.diversityPercent}%</strong><p>{stats.activeGames}/{GAMES.length} {copy('game dimainkan','games played')}</p></article><article><span><Icon name="clock" size={20}/></span><small>{copy('HARI AKTIF','ACTIVE DAYS')}</small><strong>{stats.activeDays}</strong><p>{copy(`Best activity streak ${stats.activityBest} hari`,`Best activity streak ${stats.activityBest} days`)}</p></article></section>

    <section className="statistics-grid"><article className="stats-panel wide"><header><div><span className="eyebrow">7 DAYS</span><h2>{copy('Aktivitas minggu ini','Activity this week')}</h2></div><strong>{stats.weekSessions} {copy('sesi','sessions')}</strong></header><div className="activity-chart" aria-label={copy('Grafik sesi tujuh hari','Seven-day session chart')}>{stats.last7.map(day=><div key={day.dateKey} className="chart-day"><div className="chart-bars"><i className="session-bar" style={{height:`${Math.max(day.sessions?8:2,(day.sessions/maxSessions)*100)}%`}} title={`${day.sessions} sessions`}/><i className="xp-bar" style={{height:`${Math.max(day.xp?8:2,(day.xp/maxXp)*100)}%`}} title={`${day.xp} XP`}/></div><span>{dayLabel(day.dateKey,lang)}</span><small>{day.sessions}</small></div>)}</div><div className="chart-legend"><span><i className="session-dot"/>{copy('Sesi','Sessions')}</span><span><i className="xp-dot"/>XP</span></div></article>
      <article className="stats-panel"><header><div><span className="eyebrow">BALANCE</span><h2>{copy('Kategori permainan','Game categories')}</h2></div></header><div className="category-distribution">{stats.categoryStats.map((item,index)=>{const percent=Math.round((item.completions/totalCategory)*100);return <div key={item.category}><span><i className={`category-stat-dot stat-${index}`}/><strong>{CATEGORIES[item.category][lang]}</strong></span><b>{percent}%</b><small>{item.completions} {copy('sesi','sessions')}</small><i><b className={`stat-fill-${index}`} style={{width:`${percent}%`}}/></i></div>;})}</div></article>
    </section>

    <section className="statistics-grid lower"><article className="stats-panel"><header><div><span className="eyebrow">28 DAYS</span><h2>{copy('Konsistensi aktivitas','Activity consistency')}</h2></div></header><div className="heatmap" aria-label={copy('Aktivitas 28 hari','28-day activity')}>{stats.last28.map(day=><span key={day.dateKey} className={`heat-${Math.min(4,day.sessions)}`} title={`${day.dateKey}: ${day.sessions} sessions`}/>)}</div><div className="heat-legend"><span>{copy('Lebih sedikit','Less')}</span>{[0,1,2,3,4].map(v=><i key={v} className={`heat-${v}`}/>)}<span>{copy('Lebih banyak','More')}</span></div></article>
      <article className="stats-panel"><header><div><span className="eyebrow">INSIGHT</span><h2>{copy('Ringkasan performa','Performance summary')}</h2></div></header><div className="insight-list"><div><span><Icon name="trophy" size={17}/></span><p><small>{copy('Paling sering dimainkan','Most played')}</small><strong>{stats.mostPlayed?.game.title[lang]||'—'}</strong></p><b>{stats.mostPlayed?.completions||0}</b></div><div><span><Icon name="spark" size={17}/></span><p><small>{copy('Daily Challenge selesai','Daily Challenges completed')}</small><strong>{stats.dailyDone}</strong></p><b>{stats.dailyDone}</b></div><div><span><Icon name="grid" size={17}/></span><p><small>{copy('Game belum dijelajahi','Games not explored')}</small><strong>{GAMES.length-stats.activeGames}</strong></p><button onClick={()=>onNavigate('games')}>{copy('Jelajahi','Explore')}<Icon name="arrow" size={12}/></button></div></div></article>
    </section>

    <section className="stats-panel game-performance"><header><div><span className="eyebrow">PER GAME</span><h2>{copy('Performa setiap arena','Performance by arena')}</h2></div></header><div className="stats-game-table"><div className="stats-table-head"><span>{copy('Game','Game')}</span><span>{copy('Sesi','Sessions')}</span><span>XP</span><span>{copy('Porsi','Share')}</span></div>{stats.gameStats.map(item=>{const share=stats.totalSessions?Math.round((item.completions/stats.totalSessions)*100):0;return <button key={item.game.id} onClick={()=>onNavigate(item.game.id)}><span><i className={`mini-game-icon color-${item.game.color}`}><Icon name={item.game.icon} size={15}/></i><strong>{item.game.title[lang]}</strong></span><b>{item.completions}</b><b>{item.xp}</b><span className="share-cell"><i><b style={{width:`${share}%`}}/></i><small>{share}%</small></span></button>;})}</div></section>
    <section className="stats-panel performance-game-v2"><header><div><span className="eyebrow">COMPETITIVE PER GAME</span><h2>{copy('Kualitas run per game','Run quality by game')}</h2></div></header><div className="performance-v2-table"><div className="performance-v2-head"><span>{copy('Game','Game')}</span><span>{copy('Sesi','Sessions')}</span><span>{copy('Performa','Performance')}</span><span>{copy('Win rate','Win rate')}</span><span>{copy('Waktu rata-rata','Avg time')}</span></div>{performance.perGame.filter(item=>item.sessions>0).map(item=><button key={item.game.id} onClick={()=>onNavigate(item.game.id)}><span><i className={`mini-game-icon color-${item.game.color}`}><Icon name={item.game.icon} size={15}/></i><strong>{item.game.title[lang]}</strong></span><b>{item.sessions}</b><b>{item.avgPerformance}/100</b><b>{item.winRate}%</b><span>{formatDuration(item.avgDuration)}</span></button>)}</div></section>
  </div>;
}
