import React, { useCallback, useEffect, useRef, useState } from 'react';
import GameScreen from '../components/GameScreen.jsx';
import Icon from '../components/Icon.jsx';
import RulesModal from '../components/RulesModal.jsx';
import { SetupCard, TipsButton, SoloEndCard, UniversityDifficultySelector } from '../components/GameShell.jsx';
import { useLanguage } from '../context/LanguageContext.jsx';
import { addRandomTile, canMove2048, create2048, move2048 } from '../utils/game2048.js';

const TARGETS={sd:128,smp:256,sma:512}; const UNI={hard:1024,'very-hard':2048,impossible:4096}; const UL={hard:'Hard','very-hard':'Very Hard',impossible:'Impossible'};
const KEY={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};
export default function Game2048({onBack,onNavigate}) {
  const {lang}=useLanguage(); const copy=(id,en)=>lang==='en'?en:id;
  const [showRules,setShowRules]=useState(false); const [state,setState]=useState('setup'); const [level,setLevel]=useState('sd'); const [uni,setUni]=useState('hard');
  const [board,setBoard]=useState(()=>Array(16).fill(0)); const [score,setScore]=useState(0); const [moves,setMoves]=useState(0); const touch=useRef(null);
  const target=level==='universitas'?UNI[uni]:TARGETS[level];
  const start=useCallback(()=>{setBoard(create2048());setScore(0);setMoves(0);setState('playing');},[]);
  const move=useCallback(direction=>{ if(state!=='playing') return; const result=move2048(board,direction); if(!result.moved) return; const next=addRandomTile(result.board); const nextScore=score+result.score; setBoard(next); setScore(nextScore); setMoves(v=>v+1); if(Math.max(...next)>=target) setTimeout(()=>setState('ended'),100); else if(!canMove2048(next)) setTimeout(()=>setState('ended'),100); },[board,score,state,target]);
  useEffect(()=>{const handler=e=>{const dir=KEY[e.key];if(!dir)return;const el=e.target;if(['INPUT','TEXTAREA','SELECT'].includes(el?.tagName)||el?.isContentEditable)return;e.preventDefault();move(dir);};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[move]);
  const won=Math.max(...board)>=target;
  const descriptions={sd:copy('Target 128 · Kenali cara menggabungkan ubin tanpa memenuhi papan.','Target 128 · Learn merging without filling the board.'),smp:copy('Target 256 · Mulai bangun sudut utama dan rantai angka.','Target 256 · Build a main corner and number chain.'),sma:copy('Target 512 · Perlu disiplin arah dan perencanaan beberapa langkah.','Target 512 · Requires directional discipline and multi-move planning.'),universitas:copy(`Target ${target} · ${UL[uni]} · Jaga ubin terbesar tetap terkunci di sudut.`,`Target ${target} · ${UL[uni]} · Keep your largest tile anchored in a corner.`)};
  const rules=lang==='en'?['Use Arrow Keys/WASD, swipe, or the D-pad to slide every tile.','Equal tiles merge when they collide. Each merged value is added to your score.','The opening tiles and every new 2 or 4 use randomized empty positions after valid moves.','Reach the target tile to complete the challenge.','University Arena Mode uses Hard (1024), Very Hard (2048), and Impossible (4096).' ]:[ 'Gunakan panah/WASD, swipe, atau D-pad untuk menggeser semua ubin.','Ubin bernilai sama bergabung saat bertabrakan. Nilai gabungan menambah skor.','Posisi dua ubin awal dan setiap angka 2 atau 4 baru selalu dipilih secara acak dari petak kosong.','Capai ubin target untuk menyelesaikan tantangan.','Mode Arena Universitas memakai Hard (1024), Very Hard (2048), dan Impossible (4096).' ];
  const tileClass=value=>value>=2048?'t-super':value>=512?'t-512':value>=128?'t-128':value>=32?'t-32':value>=8?'t-8':value?'t-base':'empty';
  const swipeStart=e=>{const p=e.touches?.[0];if(p)touch.current={x:p.clientX,y:p.clientY};}; const swipeEnd=e=>{if(!touch.current)return;const p=e.changedTouches?.[0];if(!p)return;const dx=p.clientX-touch.current.x,dy=p.clientY-touch.current.y;touch.current=null;if(Math.max(Math.abs(dx),Math.abs(dy))<25)return;move(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));};
  const stats=state==='playing'?<><span><Icon name="hash" size={14}/>{score.toLocaleString()}</span><span><Icon name="grid" size={14}/>{copy('Target','Target')} {target}</span></>:null;
  return <GameScreen gameId="game2048" lang={lang} state={state} level={level} onBack={onBack} onNavigate={onNavigate} onRules={()=>setShowRules(true)} stats={stats}>
    {state==='setup'&&<SetupCard heading={copy('Pilih target 2048','Choose your 2048 target')} schoolLevel={level} onLevelChange={setLevel} desc={descriptions[level]} lang={lang} badge={`${copy('Target','Target')} ${target}`}>
      {level==='universitas'&&<UniversityDifficultySelector value={uni} onChange={setUni} lang={lang}/>}<button className="uw-btn uw-btn-primary" onClick={start}><Icon name="play" size={16}/>{copy('Mulai 2048','Start 2048')}</button><TipsButton lang={lang} onClick={()=>onNavigate?.('tips-game2048')}/>
    </SetupCard>}
    {state==='playing'&&<div className="g2048-gameplay"><div className="g2048-toolbar"><div><span className="play-kicker">2048</span><strong>{copy('Target','Target')} {target}</strong><small>{copy('Gabungkan angka yang sama tanpa memutus rantai terbesar.','Merge equal numbers without breaking your largest chain.')}</small></div><button onClick={start}><Icon name="refresh" size={15}/>{copy('Ulang','Restart')}</button></div><div className="g2048-board" onTouchStart={swipeStart} onTouchEnd={swipeEnd}>{board.map((value,index)=><div key={index} className={`g2048-tile ${tileClass(value)}`}>{value||''}</div>)}</div><div className="g2048-dpad" role="group" aria-label={copy('Kontrol arah','Direction controls')}><button onClick={()=>move('up')}>↑</button><button onClick={()=>move('left')}>←</button><button onClick={()=>move('down')}>↓</button><button onClick={()=>move('right')}>→</button></div><p className="nonogram-hint">{copy('Desktop: panah / WASD · Mobile: swipe atau tombol arah.','Desktop: arrows / WASD · Mobile: swipe or direction buttons.')}</p></div>}
    {state==='ended'&&<SoloEndCard heading={won?copy(`Ubin ${target} tercapai!`,`You reached ${target}!`):copy('Papan terkunci.','No moves left.')} subtext={won?copy('Strategi sudutmu berhasil. Coba target berikutnya atau kejar skor lebih tinggi.','Your corner strategy worked. Try the next target or chase a higher score.'):copy('Tidak ada langkah valid tersisa. Susun rantai lebih rapat pada percobaan berikutnya.','No valid moves remain. Build a tighter chain next run.')} onBack={onBack} onPlayAgain={start} lang={lang} outcome={won?'completed':'loss'} stats={[{label:copy('Skor','Score'),value:score.toLocaleString()},{label:copy('Langkah','Moves'),value:moves},{label:copy('Ubin terbesar','Largest tile'),value:Math.max(...board)}]}><button type="button" className="ms-change-level" onClick={()=>setState('setup')}>{copy('Ganti target','Change target')}</button></SoloEndCard>}
    <RulesModal isOpen={showRules} onClose={()=>setShowRules(false)} gameName="2048" ruleList={rules}/>
  </GameScreen>;
}
