import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useLanguage } from '../context/LanguageContext.jsx';
import { useArena } from '../context/ArenaContext.jsx';
import { GAMES, CATEGORIES, gameById } from '../data/games.js';
import Icon from './Icon.jsx';
import Dialog from './Dialog.jsx';
import PwaInstallButton from './PwaInstallButton.jsx';
import PwaUpdateManager from './PwaUpdateManager.jsx';
import OnboardingTour from './OnboardingTour.jsx';

function isNavActive(itemId,currentView){ return currentView===itemId || (itemId==='guides'&&currentView.startsWith('tips-')) || (itemId==='profile'&&currentView==='customize'); }
function buildNav(copy,dailyCompleted,favoritesLength){ return [
  {id:'home',icon:'home',label:copy('Beranda','Overview'),group:'arena'},
  {id:'daily',icon:'spark',label:'Daily Challenge',count:dailyCompleted?'✓':null,group:'arena'},
  {id:'daily-archive',icon:'clock',label:copy('Daily Archive','Daily Archive'),group:'arena'},
  {id:'games',icon:'grid',label:copy('Semua permainan','All games'),count:GAMES.length,group:'arena'},
  {id:'favorites',icon:'star',label:copy('Favorit','Favorites'),count:favoritesLength||null,group:'arena'},
  {id:'activity',icon:'activity',label:copy('Aktivitas saya','My activity'),group:'arena'},
  {id:'guides',icon:'book',label:copy('Panduan bermain','Game guides'),group:'arena'},
  {id:'arena-run',icon:'gamepad',label:'Arena Run',group:'competitive'},
  {id:'arena-builder',icon:'sliders',label:copy('Arena Builder','Arena Builder'),group:'competitive'},
  {id:'history',icon:'clock',label:'Match History',group:'competitive'},
  {id:'leaderboard',icon:'trophy',label:'Leaderboard',group:'competitive'},
  {id:'season',icon:'spark',label:'Season',group:'competitive'},
  {id:'events',icon:'bolt',label:copy('Event','Events'),group:'competitive'},
  {id:'achievements',icon:'medal',label:copy('Achievement & Badge','Achievements & Badges'),group:'progress'},
  {id:'missions',icon:'checklist',label:copy('Mission / Quest','Missions / Quests'),group:'progress'},
  {id:'rank',icon:'shield',label:'Arena Rank',group:'progress'},
  {id:'mastery',icon:'trophy',label:'Game Mastery',group:'progress'},
  {id:'completion',icon:'medal',label:'Game Completion',group:'progress'},
  {id:'statistics',icon:'activity',label:copy('Statistik','Statistics'),group:'progress'},
  {id:'goals',icon:'flag',label:copy('Target Personal','Personal Goals'),group:'progress'},
  {id:'settings',icon:'sliders',label:copy('Pengaturan','Settings'),group:'other'},
  {id:'data-health',icon:'shield',label:copy('Data Health','Data Health'),group:'other'},
  {id:'offline',icon:'download',label:copy('Offline Manager','Offline Manager'),group:'other'},
  {id:'feedback',icon:'message',label:copy('Feedback & Saran','Feedback & Suggestions'),group:'other'},
  {id:'profile',icon:'user',label:copy('Profil pemain','Player profile'),group:'other'},
]; }

function readSidebarGroups(){ try { const raw=JSON.parse(localStorage.getItem('ba_sidebar_layout_v2')||'null'); return raw?.groups||{arena:true,competitive:true,progress:true,other:true,games:false}; } catch { return {arena:true,competitive:true,progress:true,other:true,games:false}; } }
function Navigation({currentView,onNavigate}){
  const {lang}=useLanguage();
  const {favorites,profile,levelInfo,dailyCompleted,rankInfo,avatarOption,frameOption}=useArena();
  const copy=(id,en)=>lang==='id'?id:en;
  const nav=useMemo(()=>buildNav(copy,dailyCompleted,favorites.length),[lang,dailyCompleted,favorites.length]);
  const [groups,setGroups]=useState(readSidebarGroups);
  const groupInfo=[
    ['arena',copy('ARENA','ARENA')],['competitive',copy('KOMPETITIF','COMPETITIVE')],['progress',copy('PROGRES','PROGRESS')],['other',copy('LAINNYA','OTHER')]
  ];
  const toggleGroup=id=>setGroups(prev=>{ const next={...prev,[id]:!prev[id]}; try { const old=JSON.parse(localStorage.getItem('ba_sidebar_layout_v2')||'{}'); localStorage.setItem('ba_sidebar_layout_v2',JSON.stringify({...old,groups:next})); } catch {} return next; });
  const renderItem=item=><button className={`nav-item ${isNavActive(item.id,currentView)?'active':''}`} key={item.id} onClick={()=>onNavigate(item.id)} aria-current={isNavActive(item.id,currentView)?'page':undefined}><Icon name={item.icon} size={19}/><span>{item.label}</span>{item.count!=null&&<span className="nav-count">{item.count}</span>}</button>;
  const pinned=favorites.map(gameById).filter(Boolean).slice(0,4);
  return <>
    <button className="brand" onClick={()=>onNavigate('home')} aria-label="Brain Arena - Home"><span className="brand-mark"><Icon name="cube" size={26}/></span><span><strong>brain<span>arena</span><i/></strong><small>PLAY WITH YOUR MIND</small></span></button>
    <nav aria-label={copy('Navigasi utama','Main navigation')} className="main-nav smart-nav">
      {groupInfo.map(([id,label])=><section className="smart-nav-group" key={id}><button type="button" className="nav-label nav-group-toggle" onClick={()=>toggleGroup(id)} aria-expanded={groups[id]}><span>{label}</span><Icon name={groups[id]?'down':'chevron'} size={11}/></button>{groups[id]&&<div className="smart-nav-items">{nav.filter(item=>item.group===id).map(renderItem)}</div>}</section>)}
    </nav>
    {pinned.length>0&&<nav className="game-nav pinned-game-nav" aria-label={copy('Game dipin','Pinned games')}><p className="nav-label">{copy('FAVORIT CEPAT','PINNED GAMES')}</p>{pinned.map(game=><button key={game.id} onClick={()=>onNavigate(game.id)} className={`game-nav-item ${currentView===game.id?'active':''}`}><span className={`nav-game-icon color-${game.color}`}><Icon name={game.icon} size={15}/></span><span>{game.title[lang]}</span><Icon name="star" size={12}/></button>)}</nav>}
    <nav aria-label={copy('Pintasan permainan','Game shortcuts')} className="game-nav"><button type="button" className="nav-label nav-group-toggle" onClick={()=>toggleGroup('games')} aria-expanded={groups.games}><span>{copy('LANGSUNG MAIN','JUMP INTO A GAME')}</span><Icon name={groups.games?'down':'chevron'} size={11}/></button>{groups.games&&GAMES.map(game=><button key={game.id} onClick={()=>onNavigate(game.id)} className={`game-nav-item ${currentView===game.id?'active':''}`} aria-current={currentView===game.id?'page':undefined}><span className={`nav-game-icon color-${game.color}`}><Icon name={game.icon} size={15}/></span><span>{game.title[lang]}</span>{game.season>1&&<span className="mini-tag">S{game.season}</span>}</button>)}</nav>
    <div className="sidebar-bottom"><div className="sidebar-pwa"><PwaInstallButton/></div><div className="sidebar-note"><span className="note-spark">+</span><h3>{copy('Sedikit latihan.','A little practice.')}<br/>{copy('Banyak kemajuan.','A lot of progress.')}</h3><p>{copy('Tantangan berikutnya menantimu.','Your next challenge is waiting.')}</p><button onClick={()=>onNavigate(GAMES[Math.floor(Math.random()*GAMES.length)].id)}>{copy('Coba game acak','Try a random game')}<Icon name="shuffle" size={14}/></button></div><button className="local-profile" onClick={()=>onNavigate('profile')}><span className={`profile-avatar frame-${frameOption.id}`}><Icon name={avatarOption.icon} size={18}/></span><span><strong>{profile.name||copy('Pemain lokal','Local player')}</strong><small>{rankInfo.tier.title[lang]} · Lv. {levelInfo.level}</small></span><span className="local-profile-level">{Math.round(levelInfo.progress)}%</span></button></div>
  </>;
}

function RailNavigation({currentView,onNavigate}){
  const {lang}=useLanguage(); const {favorites,dailyCompleted}=useArena(); const copy=(id,en)=>lang==='id'?id:en;
  const nav=useMemo(()=>buildNav(copy,dailyCompleted,favorites.length),[lang,dailyCompleted,favorites.length]);
  const ids=['home','daily','games','favorites','arena-run','leaderboard','achievements','missions','rank','statistics','settings','profile'];
  return <><button className="brand brand-compact" onClick={()=>onNavigate('home')} aria-label="Brain Arena - Home compact"><span className="brand-mark"><Icon name="cube" size={22}/></span></button><div className="rail-separator"/><nav className="rail-nav" aria-label={copy('Navigasi cepat','Quick navigation')}>{nav.filter(item=>ids.includes(item.id)).map(item=><button key={item.id} className={`rail-item ${isNavActive(item.id,currentView)?'active':''}`} onClick={()=>onNavigate(item.id)} aria-label={item.label} title={item.label}><Icon name={item.icon} size={18}/>{item.count!=null&&<span className="rail-dot">{item.count==='✓'?'•':item.count}</span>}</button>)}</nav><div className="rail-footer"><button className="rail-item rail-highlight" onClick={()=>onNavigate(GAMES[0].id)} title={GAMES[0].title[lang]}><Icon name={GAMES[0].icon} size={18}/></button></div></>;
}

export default function Layout({children,currentView,onViewChange}){
  const {lang,toggleLang}=useLanguage();
  const {muted,toggleSound,storageOk,notice,profile,levelInfo,rankInfo,avatarOption,frameOption,accessibility,updateAccessibility,currentSession,requestCoachHint,arenaRun,notifications,unreadNotifications,markNotificationRead,markAllNotificationsRead,recoverySession,resumeRecovery}=useArena();
  const [menu,setMenu]=useState(false),[search,setSearch]=useState(false),[help,setHelp]=useState(false),[notificationsOpen,setNotificationsOpen]=useState(false),[query,setQuery]=useState(''),[focus,setFocus]=useState(false),[coachOpen,setCoachOpen]=useState(false),[coachData,setCoachData]=useState(null),[sessionNow,setSessionNow]=useState(Date.now());
  const [sidebarCollapsed,setSidebarCollapsed]=useState(()=>{try{return localStorage.getItem('ba_sidebar_collapsed')==='1';}catch{return false;}});
  const copy=(id,en)=>lang==='id'?id:en;
  const activeGame=gameById(currentView);
  const navigate=useCallback(view=>{setMenu(false);setSearch(false);setNotificationsOpen(false);setQuery('');onViewChange(view);},[onViewChange]);
  const toggleSidebar=useCallback(()=>setSidebarCollapsed(value=>!value),[]);
  useEffect(()=>{try{localStorage.setItem('ba_sidebar_collapsed',sidebarCollapsed?'1':'0');const old=JSON.parse(localStorage.getItem('ba_sidebar_layout_v2')||'{}');localStorage.setItem('ba_sidebar_layout_v2',JSON.stringify({...old,mode:sidebarCollapsed?'compact':'full'}));}catch{}},[sidebarCollapsed]);
  useEffect(()=>{if(!activeGame)setFocus(false);},[activeGame]);
  useEffect(()=>{if(!activeGame||!currentSession?.active||currentSession.gameId!==activeGame.id)return;const timer=setInterval(()=>setSessionNow(Date.now()),1000);return()=>clearInterval(timer);},[activeGame,currentSession?.active,currentSession?.gameId]);
  useEffect(()=>{const handleKey=e=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='s'){e.preventDefault();toggleSidebar();return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(v=>!v);return;}const el=e.target;if(['INPUT','TEXTAREA','SELECT'].includes(el?.tagName)||el?.isContentEditable)return;if(e.altKey&&e.key.toLowerCase()==='h'){e.preventDefault();navigate('home');}if(e.altKey&&e.key.toLowerCase()==='l'){e.preventDefault();toggleLang();}if(e.altKey&&e.key.toLowerCase()==='m'){e.preventDefault();toggleSound();}if(e.key==='?'&&!e.altKey&&!e.ctrlKey&&!e.metaKey){e.preventDefault();setHelp(true);}};window.addEventListener('keydown',handleKey);return()=>window.removeEventListener('keydown',handleKey);},[navigate,toggleLang,toggleSound,toggleSidebar]);
  const names={home:copy('Beranda','Overview'),daily:'Daily Challenge','daily-archive':'Daily Archive',games:copy('Semua permainan','All games'),favorites:copy('Favorit','Favorites'),activity:copy('Aktivitas saya','My activity'),guides:copy('Panduan bermain','Game guides'),achievements:'Achievement & Badge',missions:'Mission / Quest',leaderboard:'Leaderboard',rank:'Arena Rank',customize:copy('Kustomisasi profil','Profile customization'),statistics:copy('Statistik lanjutan','Advanced statistics'),goals:copy('Target Personal','Personal Goals'),season:'Season',events:copy('Event','Events'),mastery:'Game Mastery','arena-run':'Arena Run','arena-builder':'Arena Builder',history:'Match History',replay:'Replay',completion:'Game Completion',settings:copy('Pengaturan & Data','Settings & Data'),'data-health':'Data Health',offline:'Offline Manager',challenge:'Challenge',feedback:copy('Feedback & Saran','Feedback & Suggestions'),profile:copy('Profil pemain','Player profile')};
  const currentName=activeGame?.title[lang]||(currentView.startsWith('tips-')?`${copy('Panduan','Guide')} / ${gameById(currentView.slice(5))?.title[lang]||''}`:names[currentView]||copy('Halaman tidak ditemukan','Page not found'));
  const normalized=query.trim().toLocaleLowerCase();
  const gameResults=GAMES.filter(g=>`${g.title.id} ${g.title.en} ${CATEGORIES[g.category][lang]}`.toLocaleLowerCase().includes(normalized));
  const commandItems=useMemo(()=>[
    {id:'home',icon:'home',label:copy('Buka Beranda','Open Home'),keywords:'home beranda',run:()=>navigate('home')},
    {id:'daily',icon:'spark',label:copy('Buka Daily Challenge','Open Daily Challenge'),keywords:'daily challenge',run:()=>navigate('daily')},
    {id:'archive',icon:'clock',label:copy('Buka Daily Archive','Open Daily Archive'),keywords:'archive arsip daily',run:()=>navigate('daily-archive')},
    {id:'builder',icon:'sliders',label:copy('Buka Arena Builder','Open Arena Builder'),keywords:'custom arena builder tournament',run:()=>navigate('arena-builder')},
    {id:'goals',icon:'flag',label:copy('Buka Target Personal','Open Personal Goals'),keywords:'goal target personal',run:()=>navigate('goals')},
    {id:'health',icon:'shield',label:copy('Periksa Data Health','Check Data Health'),keywords:'data health repair restore',run:()=>navigate('data-health')},
    {id:'offline',icon:'download',label:copy('Kelola Konten Offline','Manage Offline Content'),keywords:'offline download cache pwa',run:()=>navigate('offline')},
    {id:'sidebar',icon:'sidebar',label:copy('Ubah Sidebar','Toggle Sidebar'),keywords:'sidebar compact full',run:toggleSidebar},
    {id:'notifications',icon:'bell',label:copy('Buka Notifikasi','Open Notifications'),keywords:'notification notifikasi inbox',run:()=>{setSearch(false);setNotificationsOpen(true);}},
    {id:'sound',icon:muted?'muted':'sound',label:muted?copy('Aktifkan suara','Unmute sound'):copy('Bisukan suara','Mute sound'),keywords:'sound suara mute',run:toggleSound},
    {id:'language',icon:'globe',label:copy('Ganti bahasa','Switch language'),keywords:'language bahasa english indonesia',run:toggleLang},
    {id:'dark',icon:'moon',label:copy('Aktifkan Dark Mode','Enable Dark Mode'),keywords:'dark theme tema gelap',run:()=>updateAccessibility('theme','dark')},
    {id:'light',icon:'sun',label:copy('Aktifkan Light Mode','Enable Light Mode'),keywords:'light theme tema terang',run:()=>updateAccessibility('theme','light')},
    {id:'settings',icon:'sliders',label:copy('Pengaturan & Backup','Settings & Backup'),keywords:'settings backup export import',run:()=>navigate('settings')},
    {id:'profile',icon:'user',label:copy('Buka Profil','Open Profile'),keywords:'profile profil pemain',run:()=>navigate('profile')},
  ],[copy,navigate,toggleSidebar,muted,toggleSound,toggleLang,updateAccessibility]);
  const commandResults=commandItems.filter(item=>!normalized||`${item.label} ${item.keywords}`.toLocaleLowerCase().includes(normalized));
  const activeSession=activeGame&&currentSession?.gameId===activeGame.id?currentSession:null;
  const sessionElapsed=activeSession?.startedAt?Math.max(0,sessionNow-activeSession.startedAt):0;
  const fmt=ms=>{const sec=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;};
  const openCoach=()=>{if(!activeGame)return;setCoachData(requestCoachHint(activeGame.id,lang));setCoachOpen(true);};
  const openNotification=item=>{markNotificationRead(item.id);if(item.type==='recovery'&&recoverySession){const target=resumeRecovery();if(target)navigate(target);return;}if(item.route)navigate(item.route);};
  return <div className={`ba-app ${focus?'is-focus':''} ${sidebarCollapsed?'sidebar-collapsed':'sidebar-expanded'} theme-${accessibility.theme} ${accessibility.reducedMotion?'reduce-motion':''} ${accessibility.highContrast?'high-contrast':''} ${accessibility.largeText?'large-text':''}`}>
    <a href="#main-content" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus();}}>{copy('Lewati ke konten','Skip to content')}</a>
    <aside className="sidebar"><Navigation currentView={currentView} onNavigate={navigate}/></aside><aside className="sidebar-rail"><RailNavigation currentView={currentView} onNavigate={navigate}/></aside>
    <div className="app-body"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" onClick={()=>setMenu(true)} aria-label={copy('Buka menu navigasi','Open navigation menu')}><Icon name="menu"/></button><button className="icon-button sidebar-toggle" onClick={toggleSidebar} aria-pressed={sidebarCollapsed} aria-label={copy('Ubah sidebar','Toggle sidebar')} title={`${copy('Ubah sidebar','Toggle sidebar')} · Ctrl+Shift+S`}><Icon name="sidebar" size={18}/></button><div className="breadcrumb"><button onClick={()=>navigate('home')}><Icon name="home" size={15}/><span>Arena</span></button><Icon name="chevron" size={12}/><span>{currentName}</span></div></div><div className="topbar-actions"><button className="global-search" onClick={()=>setSearch(true)} aria-label={copy('Command palette (Ctrl K)','Command palette (Ctrl K)')}><Icon name="search" size={16}/><span>{copy('Cari game atau aksi...','Search games or actions...')}</span><kbd>Ctrl K</kbd></button><span className="toolbar-divider"/><button className="language-button" onClick={toggleLang}><Icon name="globe" size={17}/>{lang.toUpperCase()}<Icon name="down" size={11}/></button><button className="icon-button sound-button" onClick={toggleSound} aria-pressed={muted}><Icon name={muted?'muted':'sound'} size={18}/></button>{activeGame&&<button className="icon-button" onClick={()=>setFocus(!focus)} aria-pressed={focus}><Icon name={focus?'collapse':'expand'} size={18}/></button>}{activeGame&&<button className="icon-button coach-top-button" onClick={openCoach}><Icon name="brain" size={18}/></button>}<PwaInstallButton compact/><button className="icon-button notification-button" onClick={()=>setNotificationsOpen(true)} aria-label={copy('Buka notifikasi','Open notifications')}><Icon name="bell" size={18}/>{unreadNotifications>0&&<span>{Math.min(99,unreadNotifications)}</span>}</button><button className="topbar-profile" onClick={()=>navigate('profile')}><span className={`frame-${frameOption.id}`}><Icon name={avatarOption.icon} size={15}/></span><span><strong>{profile.name||copy('Pemain Lokal','Local Player')}</strong><small>{rankInfo.tier.title[lang]} · Lv. {levelInfo.level}</small></span><i><b style={{width:`${levelInfo.progress}%`}}/></i></button><button className="icon-button help-button" onClick={()=>setHelp(true)}><Icon name="help" size={19}/></button></div></header>
      {!storageOk&&<div className="storage-banner" role="status">{copy('Penyimpanan browser tidak tersedia. Perubahan hanya tersimpan selama tab ini terbuka.','Browser storage is unavailable. Changes will only last while this tab stays open.')}</div>}
      {activeSession?.active&&<div className="competitive-hud"><span className={`hud-mode ${activeSession.mode}`}><Icon name={activeSession.mode==='ranked'?'shield':'gamepad'} size={13}/>{activeSession.mode==='ranked'?'Ranked':'Practice'}</span><span><Icon name="clock" size={13}/>{fmt(sessionElapsed)}</span>{activeSession.personalBestMs>0&&<span><Icon name="ghost" size={13}/>PB {fmt(activeSession.personalBestMs)}</span>}<code>{activeSession.challengeCode}</code>{arenaRun?.status==='active'&&activeSession.arenaRunId===arenaRun.id&&<span className="hud-run"><Icon name="trophy" size={13}/>{copy('Arena','Arena')} {arenaRun.index+1}/{arenaRun.stages.length}</span>}<button onClick={openCoach}><Icon name="brain" size={13}/>Brain Coach{activeSession.mode==='ranked'?` ${Math.max(0,2-(activeSession.hintsUsed||0))}/2`:''}</button></div>}
      <main id="main-content" tabIndex={-1} className={`main-content ${activeGame?'game-page':''}`}>{children}</main><footer className="site-footer"><span><strong>brainarena.</strong> {copy('Tempat pikiran bertumbuh.','Where sharp minds play.')}</span><span>{copy('Proyek penggemar independen','An independent fan project')}<i/>{copy('Dibuat untuk terus belajar','Built to keep you learning')}</span></footer>
    </div>
    <PwaUpdateManager/><OnboardingTour onNavigate={navigate}/>
    <Dialog open={menu} onClose={()=>setMenu(false)} title={copy('Navigasi','Navigation')} className="mobile-menu-dialog"><Navigation currentView={currentView} onNavigate={navigate}/></Dialog>
    <Dialog open={search} onClose={()=>{setSearch(false);setQuery('');}} title={copy('Command Palette','Command Palette')} className="search-dialog command-dialog"><label className="command-input"><Icon name="search"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={copy('Cari game, halaman, atau aksi...','Search games, pages, or actions...')}/></label><div className="command-section"><small>{copy('AKSI CEPAT','QUICK ACTIONS')}</small><div className="search-results command-results">{commandResults.map(item=><button key={item.id} onClick={()=>{item.run();setSearch(false);setQuery('');}}><span className="command-result-icon"><Icon name={item.icon} size={16}/></span><span><strong>{item.label}</strong><small>{copy('Aksi Brain Arena','Brain Arena action')}</small></span><Icon name="arrow" size={15}/></button>)}</div></div><div className="command-section"><small>{copy('PERMAINAN','GAMES')}</small><div className="search-results">{gameResults.length?gameResults.map(g=><button key={g.id} onClick={()=>navigate(g.id)}><span className={`mini-game-icon color-${g.color}`}><Icon name={g.icon}/></span><span><strong>{g.title[lang]}</strong><small>{CATEGORIES[g.category][lang]} · {copy('Musim','Season')} {g.season}</small></span><Icon name="arrow" size={17}/></button>):<p className="search-empty">{copy('Tidak ada game yang cocok.','No matching games.')}</p>}</div></div><p className="dialog-footnote"><kbd>Ctrl K</kbd> {copy('buka/tutup','open/close')} &nbsp; <kbd>Esc</kbd> {copy('tutup','close')}</p></Dialog>
    <Dialog open={notificationsOpen} onClose={()=>setNotificationsOpen(false)} title={copy('Notification Center','Notification Center')} className="notification-dialog"><div className="notification-toolbar"><p>{unreadNotifications?copy(`${unreadNotifications} belum dibaca`,`${unreadNotifications} unread`):copy('Semua sudah dibaca','All caught up')}</p>{notifications.length>0&&<button type="button" className="text-button" onClick={markAllNotificationsRead}>{copy('Tandai semua dibaca','Mark all read')}</button>}</div><div className="notification-list">{notifications.length?notifications.map(item=><button key={item.id} className={item.read?'is-read':''} onClick={()=>openNotification(item)}><span><Icon name={item.icon} size={17}/></span><div><strong>{item.title[lang]}</strong><p>{item.body[lang]}</p></div>{!item.read&&<i/>}</button>):<div className="notification-empty"><Icon name="bell" size={25}/><strong>{copy('Belum ada notifikasi','No notifications yet')}</strong><p>{copy('Daily, mission, season, achievement, dan recovery akan muncul di sini.','Daily, mission, season, achievement, and recovery updates will appear here.')}</p></div>}</div></Dialog>
    <Dialog open={help} onClose={()=>setHelp(false)} title={copy('Selamat datang di arena','Welcome to the arena')}><p className="dialog-description">{copy('Pilih game, tentukan tingkat pendidikan, lalu mulai tantangan. Gunakan panduan untuk mempelajari aturan dan strategi.','Choose a game, select your education level, and start a challenge. Check each guide for rules and strategies.')}</p><div className="shortcuts">{[['Ctrl + Shift + S',copy('Ubah sidebar','Toggle sidebar')],['Ctrl / Cmd + K',copy('Command Palette','Command Palette')],['Alt + H',copy('Kembali ke beranda','Return home')],['Alt + L',copy('Ganti bahasa','Switch language')],['Alt + M',copy('Aktifkan / bisukan suara','Toggle sound')],['?',copy('Buka bantuan','Open help')]].map(([key,label])=><div key={key}><span>{label}</span><kbd>{key}</kbd></div>)}</div><div className="privacy-note"><Icon name="shield"/><p>{copy('Progress, autosave, notifikasi, XP, rank, dan profil disimpan di browser ini. v1.15 memigrasikan data lama tanpa menghapus progres.','Progress, autosave, notifications, XP, rank, and profile stay in this browser. v1.15 migrates older data without deleting progress.')}</p></div><button className="ba-button primary full-width" onClick={()=>{setHelp(false);navigate('guides');}}>{copy('Lihat panduan bermain','Browse game guides')}<Icon name="arrow" size={16}/></button></Dialog>
    <Dialog open={coachOpen} onClose={()=>setCoachOpen(false)} title="Brain Coach" className="coach-dialog"><div className="coach-content"><span className="coach-orb"><Icon name="brain" size={24}/></span><div><small>{activeSession?.mode==='ranked'?copy('RANKED HINT','RANKED HINT'):copy('SMART HINT','SMART HINT')}</small><p>{coachData?.text||copy('Mulai permainan lalu gunakan Brain Coach untuk mendapatkan petunjuk strategis tanpa membuka jawaban langsung.','Start the game, then use Brain Coach for strategic guidance without revealing the answer directly.')}</p>{coachData?.limited&&<strong>{copy('Batas hint Ranked sudah tercapai.','Ranked hint limit reached.')}</strong>}</div></div>{activeGame&&<button className="ba-button primary full-width" disabled={coachData?.limited} onClick={()=>setCoachData(requestCoachHint(activeGame.id,lang))}><Icon name="spark" size={15}/>{copy('Hint berikutnya','Next hint')}</button>}</Dialog>
    <div className={`toast ${notice?'visible':''}`} role="status" aria-live="polite">{notice&&<><Icon name="check" size={17}/>{notice}</>}</div>
  </div>;
}
