import React,{useEffect,useState} from 'react';
import Dialog from './Dialog.jsx';import Icon from './Icon.jsx';import {useLanguage} from '../context/LanguageContext.jsx';import {useArena} from '../context/ArenaContext.jsx';
const KEY='ba_onboarding_v1';
export default function OnboardingTour({onNavigate}){const {lang}=useLanguage();const {grantXp,profile}=useArena();const copy=(id,en)=>lang==='id'?id:en;const [open,setOpen]=useState(false);const [step,setStep]=useState(0);useEffect(()=>{try{if(!localStorage.getItem(KEY))setOpen(true);}catch{}},[]);const steps=[
 {icon:'grid',title:copy('Pilih arena bermain','Choose your arena'),body:copy('Brain Arena punya 12 game matematika, logika, memori, dan strategi.','Brain Arena has 12 math, logic, memory, and strategy games.')},
 {icon:'spark',title:'Daily Challenge',body:copy('Satu tantangan baru setiap hari untuk XP dan streak.','A fresh daily challenge for XP and streaks.')},
 {icon:'trophy',title:copy('XP, Rank, dan Mastery','XP, Rank, and Mastery'),body:copy('Setiap sesi membangun progres akun dan penguasaan tiap game.','Every session builds account progress and per-game mastery.')},
 {icon:'gamepad',title:'Arena Run',body:copy('Gabungkan beberapa game menjadi turnamen cepat atau custom.','Combine several games into a quick or custom tournament.')},
 {icon:'menu',title:copy('Sidebar yang bisa diubah','Flexible sidebar'),body:copy('Gunakan Ctrl + Shift + S untuk Full/Compact. Ctrl + K membuka Command Palette.','Use Ctrl + Shift + S for Full/Compact. Ctrl + K opens the Command Palette.')},
 ];const finish=()=>{try{localStorage.setItem(KEY,JSON.stringify({completedAt:Date.now(),version:'1.15'}));}catch{}if (!(profile?.xpEvents||[]).some(event=>event?.source==='onboarding'&&event?.sourceId==='welcome-v115')) grantXp?.(25,{source:'onboarding',id:'welcome-v115'});setOpen(false);};const skip=()=>{try{localStorage.setItem(KEY,JSON.stringify({skippedAt:Date.now(),version:'1.15'}));}catch{}setOpen(false);};const item=steps[step];return <Dialog open={open} onClose={skip} title={copy('Selamat datang di Brain Arena','Welcome to Brain Arena')} className="onboarding-dialog"><div className="onboarding-tour"><div className="onboarding-progress">{steps.map((_,i)=><i key={i} className={i<=step?'active':''}/>)}</div><span className="onboarding-orb"><Icon name={item.icon} size={30}/></span><small>{step+1}/{steps.length}</small><h2>{item.title}</h2><p>{item.body}</p><div className="onboarding-actions"><button className="text-button" onClick={skip}>{copy('Lewati','Skip')}</button>{step>0&&<button className="ba-button outline" onClick={()=>setStep(s=>s-1)}>{copy('Kembali','Back')}</button>}<button className="ba-button primary" onClick={()=>step===steps.length-1?finish():setStep(s=>s+1)}>{step===steps.length-1?copy('Masuk Arena +25 XP','Enter Arena +25 XP'):copy('Lanjut','Next')}<Icon name="arrow" size={14}/></button></div></div></Dialog>}
